name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 1'

env:
  ALIYUN_IMAGE_TOKEN: ${{ secrets.ALIYUN_IMAGE_ACCESSTOKEN }}

jobs:
  build:
    name: Image ${{ matrix.php-mode }}-${{ matrix.php-version }}-${{ matrix.system }}-${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '7.4'
        php-mode:
          - fpm
          - cli
        system:
          - alpine
          - bullseye
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Recognize Tag
        run: |
          platform=$(echo ${{ matrix.platform }} | sed 's/linux\///g')
          tag=$platform'-'${{ matrix.php-mode }}-${{ matrix.php-version }}-${{ matrix.system }}
          echo $tag
          echo "tag=$tag" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Build the Docker image
        run: |
          docker buildx ls
          docker buildx build -t carpedx/php --platform ${{ matrix.platform }} -f ./${{ matrix.php-version }}/${{ matrix.php-mode }}/${{ matrix.system }}/Dockerfile ./${{ matrix.php-version }}/${{ matrix.php-mode }}
      - name: Tag the Image
        run: |
          docker tag carpedx/php carpedx/php:$tag
          docker tag carpedx/php registry.cn-hangzhou.aliyuncs.com/carpedx/php:$tag
      - name: Push the Image to Aliyun registry
        run: |
          echo $ALIYUN_IMAGE_TOKEN | docker login --username=870511922@qq.com registry.cn-hangzhou.aliyuncs.com --password-stdin
          docker push registry.cn-hangzhou.aliyuncs.com/carpedx/php:$tag
          docker logout